### ISSUE TITLE
Cannot read property 'incremental' of undefined

### ISSUE THREAD

**Issue by niks3089** [nimbella/commander-cli#12]
```
 nc> csm_install ./nimbella
  ✔ Packaging nimbella...
  ✔ Uploading nimbella...
Error: Cannot read property 'incremental' of undefined
```

**Comment by satyarohith** [comment]
I couldn't reproduce the issue. Maybe the new changes might fix it. Let me know if this persists after changes from #14.

**Comment by satyarohith** [comment]
Closing this for now. Feel free to re-open if the error pops up again.
