### ISSUE TITLE
command_set create doesn't work

### ISSUE THREAD

**Issue by bhageena** [nimbella/commander-cli#36]
_/nc command_set create_  fails with below message

```
/nc command_set create
Command not found, Did you mean /nc command_log ?
 nc> 
```

**Comment by v-shant** [comment]
![image](https://user-images.githubusercontent.com/35557159/111791225-048c6780-88e9-11eb-97f8-8819086e3f03.png)


command_set create will work without /nc. but Its confusing for some commands /nc works for some doesn't.
