### ISSUE TITLE
csm_install doesn't work for local project

### ISSUE THREAD

**Issue by bhageena** [nimbella/commander-cli#37]
_/nc csm_install ./github_ fails with the below message, while same setup works for remote/github path 
 
```
 /nc csm_install ./github
Error: Invalid file type. Navigate to https://nimbella.com/resources-commander/reference#csm_install for more help.
 nc> 

```

**Comment by v-shant** [comment]
same as #36, `csm_install ./github` should work without /nc . 


again its confusing as in commander we use /nc and the same user when comes to commander-cli may use /nc with commands. as there are some commander specific commands which are running with /nc  and there will be some which will not run, is confusing
